apiVersion: apps/v1
kind: Deployment
metadata:
  name: loco-assessment-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: loco-assessment
  template:
    metadata:
      labels:
        app: loco-assessment
    spec:
      containers:
        - name: loco-assessment-container
          image: gagangaga/loco-assessment:v2
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
